[msg MSG_000 [0]]
[f 0 8 65278][f 1 31][f 0 7 5]......[n][f 0 4][e]

[msg MSG_NG_000 [0]]
[f 0 8 65278][f 1 31][f 0 7 5]Bug.[n][f 0 4][e]

[msg MSG_0033 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 33]I'll try and find out the enemy's[n]weakness. Just let me know when.[n][f 2 7 10][f 0 4][e]

[msg MSG_0045 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 45]The enemy can use charm attacks![n]Please keep an eye on each other.[n][f 2 7 10][f 0 4][e]

[msg MSG_0048 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 48]Its Arcana is Justice... Wait, it's[n]Chariot? What the--[n][f 2 7 10][f 0 4][e]

[msg MSG_0049 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 49]Why am I sensing two entities...?[n]It doesn't make sense![n][f 2 7 10][f 0 4][e]

[msg MSG_0052 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 52]I see now. The vehicle and turret are[n]different types: one's Chariot and[n]the other's Justice.[n][f 2 7 10][f 0 4][e]

[msg MSG_0053 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 53]They seem to be coordinating their[n]attacks, too. Please be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_0054 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 54]Now that they're separated, maybe[n]you can knock them down![n][f 2 7 10][f 0 4][e]

[msg MSG_0057 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 57]It looks like you have to take them[n]out simultaneously![n][f 2 7 10][f 0 4][e]

[msg MSG_0059 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 59]The Shadow has a lot of electricity[n]charged up...[n][f 2 7 10][f 0 4][e]

[msg MSG_0060 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 60]Please be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_0061 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 61]Apparently, it has to charge up[n]before using that one attack.[n][f 2 7 10][f 0 4][e]

[msg MSG_0062 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 62]Please be careful whenever you see[n]the enemy charging![n][f 2 7 10][f 0 4][e]

[msg MSG_0063 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 63]Huh...? Did it just...?[n][f 2 7 10][f 0 4][e]

[msg MSG_0064 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 64]It did! It lowers its guard when[n]it's charging![n][f 2 7 10][f 0 4][e]

[msg MSG_0065 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 65]If you attack while it's charging,[n]you can probably knock it down![n][f 2 7 10][f 0 4][e]

[msg MSG_0066 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 66]But if you fail, you might get hit[n]with that nasty attack...[n][f 2 7 10][f 0 4][e]

[msg MSG_0067 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 67]Make sure you weigh your options[n]carefully.[n][f 2 7 10][f 0 4][e]

[msg MSG_0069 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 69]Huh!? One of them seems to be[n]disappearing... What's going on?[n][f 2 7 10][f 0 4][e]

[msg MSG_0070 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 70]I don't detect the Fortune one[n]anymore! The Strength one must[n]have done something![n][f 2 7 10][f 0 4][e]

[msg MSG_0071 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 71]You can't attack it right now...[n]Concentrate on the one whose[n]Arcana is Strength![n][f 2 7 10][f 0 4][e]

[msg MSG_0073 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 73]That wheel's effects depend on[n]where it stops.[n][f 2 7 10][f 0 4][e]

[msg MSG_0074 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 74]Red is bad luck... I hope it doesn't[n]come up.[n][f 2 7 10][f 0 4][e]

[msg MSG_0076 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 76]Um, I detect Fortune again! So you can[n]attack that one now![n][f 2 7 10][f 0 4][e]

[msg MSG_0762 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 905][f 0 31 17 10 2 1]Now, you shall be judged.[n][f 2 7 10][f 0 4][e]

[msg MSG_0782 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 906][f 0 31 18 10 3 1]There's no cure for stupidity...[n][f 2 7 10][f 0 4][e]

[msg MSG_0763 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 907][f 0 31 17 10 2 1]It appears you have more than just luck[n]on your side! So be it![n][f 2 7 10][f 0 4][e]

[msg MSG_0783 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 908][f 0 31 18 10 3 1]Play time's over, kids. It's time for[n]the real deal![n][f 2 7 10][f 0 4][e]

[msg MSG_0764 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 909][f 0 31 17 10 3 1]I never imagined that your power[n]would rival ours...[n][f 2 7 10][f 0 4][e]

[msg MSG_0765 [Takaya]]
[f 0 8 65278][f 1 31][f 2 11 5 910][f 0 31 17 10 5 1]Astonishing... Perhaps I misjudged[n]your strength.[n][f 2 7 10][f 0 4][e]

[msg MSG_0784 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 911][f 0 31 18 10 3 1]Oh, you're gonna pay for this![n][f 2 7 10][f 0 4][e]

[msg MSG_0766 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 912][f 0 31 17 10 5 1]Ugh... So, this is the power of those[n]whose Persona awakened naturally...[n][f 2 7 10][f 0 4][e]

[msg MSG_0785 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 913][f 0 31 18 10 3 1]Shit... These guys are tougher than[n]I thought![n][f 2 7 10][f 0 4][e]

[msg MSG_0767 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 767][f 0 31 17 10 1 5]Ugh... This can't be...[n][f 2 7 10][f 0 4][e]

[msg MSG_0786 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 786][f 0 31 18 10 1 5]Son of a bitch...![n][f 2 7 10][f 0 4][e]

[msg MSG_0082 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 82]I think that floating thing is your[n]main target, but...[n][f 2 7 10][f 0 4][e]

[msg MSG_0083 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 83]It's out of your attack range...[n][f 2 7 10][f 0 4][e]

[msg MSG_0085 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 85]Give me a minute... I'll see what[n]I can find out.[n][f 2 7 10][f 0 4][e]

[msg MSG_0086 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 86]For some reason, those statues feel[n]similar to that floating Shadow.[n][f 2 7 10][f 0 4][e]

[msg MSG_0087 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 87]They must be related somehow.[n][f 2 7 10][f 0 4][e]

[msg MSG_0090 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 90]Wait![n][f 2 7 10][f 0 4][e]

[msg MSG_0091 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 91]The one that changed colors...[n]It's stored up a lot of energy...[n][f 2 7 10][f 0 4][e]

[msg MSG_0092 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 92]I don't know what it's going to do,[n]but watch out![n][f 2 7 10][f 0 4][e]

[msg MSG_0099 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 99]*gasp* It's using those other[n]Shadows as bombs![n][f 2 7 10][f 0 4][e]

[msg MSG_0100 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 100]Watch it carefully! You can tell[n]when it's about to explode![n][f 2 7 10][f 0 4][e]

[msg MSG_0090_2 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 90]Wait![n][f 2 7 10][f 0 4][e]

[msg MSG_0091_2 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 91]The one that changed colors...[n]It's stored up a lot of energy...[n][f 2 7 10][f 0 4][e]

[msg MSG_0092_2 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 92]I don't know what it's going to do,[n]but watch out![n][f 2 7 10][f 0 4][e]

[msg MSG_0099_2 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 99]*gasp* It's using those other[n]Shadows as bombs![n][f 2 7 10][f 0 4][e]

[msg MSG_0100_2 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 100]Watch it carefully! You can tell[n]when it's about to explode![n][f 2 7 10][f 0 4][e]

[msg MSG_0802 [Chidori]]
[f 0 8 65278][f 1 31][f 2 9 5 914][f 0 31 19 10 5 1]I don't belong here...[n]I... I've always known that![n][f 2 7 10][f 0 4][e]

[msg MSG_0803 [Chidori]]
[f 0 8 65278][f 1 31][f 2 9 5 915][f 0 31 19 10 1 4]You're aware of my ability,[n]aren't you? Weak attacks are[n]useless against me.[n][f 2 7 10][f 0 4][e]

[msg MSG_0804 [Chidori]]
[f 0 8 65278][f 1 31][f 2 9 5 916][f 0 31 19 10 3 1]Takaya was right... You're a nuisance![n][f 2 7 10][f 0 4][e]

[msg MSG_0805 [Chidori]]
[f 0 8 65278][f 1 31][f 2 9 5 917][f 0 31 19 10 4 1]This pain is insignificant... The suffering[n]my heart bears is far greater![n][f 2 7 10][f 0 4][e]

[msg MSG_0806 [Chidori]]
[f 0 8 65278][f 1 31][f 2 9 5 918][f 0 31 19 10 5 1]Why!? Why won't you leave me alone!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0807 [Chidori]]
[f 0 8 65278][f 1 31][f 2 11 5 919][f 0 31 19 10 4 1]I just don't get it, Junpei...[n][f 2 7 10][f 0 4][e]

[msg MSG_0787 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 920][f 0 31 18 10 3 1]This is it... I ain't holdin' back![n][f 2 7 10][f 0 4][e]

[msg MSG_0788 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 921][f 0 31 18 10 3 1]I've improved since our last fight.[n]You can't hide your weaknesses[n]from me![n][f 2 7 10][f 0 4][e]

[msg MSG_0789 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 922][f 0 31 18 10 1 1]I excel at data analysis.[n][f 2 7 10][f 0 4][e]

[msg MSG_0790 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 923][f 0 31 18 10 1 1]I don't need no Persona to find[n]your weaknesses![n][f 0 4][e]

[msg MSG_0791 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 924][f 0 31 18 10 4 1]...Damn you! You've covered up[n]all your weaknesses![n][f 2 7 10][f 0 4][e]

[msg MSG_0792 [Jin]]
[f 0 8 65278][f 1 31][f 2 11 5 925][f 0 31 18 10 4 1]Are you too afraid to face them?[n][f 2 7 10][f 0 4][e]

[msg MSG_0793 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 926][f 0 31 18 10 3 1]Tch, you think you're tough?[n]I won't lose this time![n][f 2 7 10][f 0 4][e]

[msg MSG_0794 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 927][f 0 31 18 10 3 1]No... I ain't finished yet![n]Come on![n][f 2 7 10][f 0 4][e]

[msg MSG_0795 [Jin]]
[f 0 8 65278][f 1 31][f 2 9 5 928][f 0 31 18 10 4 1]Dammit...![n][f 2 7 10][f 0 4][e]

[msg MSG_0107 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 107]Please be careful! I sense even[n]greater power than before...![n][f 2 7 10][f 0 4][e]

[msg MSG_0768 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 929][f 0 31 17 10 2 1]You needn't hurry. The moment we await[n]is predestined.[n][f 2 7 10][f 0 4][e]

[msg MSG_0769 [Takaya]]
[f 0 8 65278][f 1 31][f 2 11 5 930][f 0 31 17 10 2 1]It's only a matter of time.[n][f 2 7 10][f 0 4][e]

[msg MSG_0770 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 931][f 0 31 17 10 2 1]Even as I speak, I can feel it.[n]The end of everything...[n][f 2 7 10][f 0 4][e]

[msg MSG_0771 [Takaya]]
[f 0 8 65278][f 1 31][f 2 11 5 932][f 0 31 17 10 2 1]I pity those who cannot see it for[n]what it truly is... a blessing.[n][f 2 7 10][f 0 4][e]

[msg MSG_0772 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 933][f 0 31 17 10 1 1]We are mere mortals; we cannot[n]change our fate.[n][f 2 7 10][f 0 4][e]

[msg MSG_0773 [Takaya]]
[f 0 8 65278][f 1 31][f 2 11 5 934][f 0 31 17 10 1 1]You would be foolish to deny it...[n][f 2 7 10][f 0 4][e]

[msg MSG_0774 [Takaya]]
[f 0 8 65278][f 1 31][f 2 9 5 935][f 0 31 17 10 1 1]Ha... Hahaha... It seems we are[n]destined to be in opposition...[n][f 2 7 10][f 0 4][e]

[msg MSG_0775 [Takaya]]
[f 0 8 65278][f 1 31][f 2 11 5 936][f 0 31 17 10 3 1]How can you summon such power...[n]even in the face of death...?[n][f 2 7 10][f 0 4][e]

[msg MSG_0110 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 110]Nyx's Arcana changed to the Magician!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0111 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 111]Be careful! Its properties have changed![n][f 2 7 10][f 0 4][e]

[msg MSG_0113 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 113]It changed properties again.[n]If you need me to analyze it,[n]just say the word.[n][f 2 7 10][f 0 4][e]

[msg MSG_0115 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 115]I sense... Death! Nyx's true Arcana[n]is Death![n][f 2 7 10][f 0 4][e]

[msg MSG_0116 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 116]W-Wait! Something's strange about[n]Nyx...[n][f 2 7 10][f 0 4][e]

[msg MSG_0117 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 117]I have a bad feeling about this...[n]It's definitely up to something![n][f 2 7 10][f 0 4][e]

[msg MSG_0118 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 118]Have everyone hold their attacks![n]It's too dangerous right now![n][f 2 7 10][f 0 4][e]

[msg MSG_0831 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 937]The moment man devoured the fruit[n]of knowledge, he sealed his fate...[n][f 2 7 10][f 0 4][e]

[msg MSG_0832 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 938]Entrusting his future to the cards,[n]man clings to a dim hope.[n][f 2 7 10][f 0 4][e]

[msg MSG_0833 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 939]Yes, the Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0834 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 940]Attaining one's dream requires a stern[n]will and unfailing determination.[n][f 2 7 10][f 0 4][e]

[msg MSG_0835 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 941]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0836 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 942]The silent voice within one's heart[n]whispers the most profound wisdom.[n][f 2 7 10][f 0 4][e]

[msg MSG_0837 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 943]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0838 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 944]Celebrate life's grandeur... its brilliance...[n]its magnificence...[n][f 2 7 10][f 0 4][e]

[msg MSG_0839 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 945]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0840 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 946]Only courage in the face of doubt[n]can lead one to the answer...[n][f 2 7 10][f 0 4][e]

[msg MSG_0841 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 947]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0842 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 948]It is indeed a precious gift to[n]understand the forces that guide[n]oneself...[n][f 2 7 10][f 0 4][e]

[msg MSG_0843 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 949]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0844 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 950]There is both joy and wonder in[n]coming to understand another...[n][f 2 7 10][f 0 4][e]

[msg MSG_0845 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 951]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0846 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 952]One of life's greatest blessings is[n]the freedom to pursue one's goals.[n][f 2 7 10][f 0 4][e]

[msg MSG_0847 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 953]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0848 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 954]To find the one true path, one must seek[n]guidance amidst uncertainty...[n][f 2 7 10][f 0 4][e]

[msg MSG_0849 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 955]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0850 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 956]It requires great courage to look at[n]oneself honestly, and forge one's[n]own path...[n][f 2 7 10][f 0 4][e]

[msg MSG_0851 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 957]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0852 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 958]Alongside time exists fate,[n]the bearer of cruelty.[n][f 2 7 10][f 0 4][e]

[msg MSG_0853 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 959]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0854 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 960]Only with strength can one endure[n]suffering and torment.[n][f 2 7 10][f 0 4][e]

[msg MSG_0855 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 961]The Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0856 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 962]In the face of disaster lies opportunity[n]for renewal.[n][f 2 7 10][f 0 4][e]

[msg MSG_0857 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 963]The moment man devoured the fruit[n]of knowledge, he sealed his fate...[n][f 2 7 10][f 0 4][e]

[msg MSG_0858 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 964]Entrusting his future to the cards,[n]man clings to a dim hope.[n][f 2 7 10][f 0 4][e]

[msg MSG_0859 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 965]Yet, the Arcana is the means by which[n]all is revealed...[n][f 2 7 10][f 0 4][e]

[msg MSG_0860 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 966]Beyond the beaten path lies[n]the absolute end.[n][f 2 7 10][f 0 4][e]

[msg MSG_0861 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 11 5 967]It matters not who you are...[n]Death awaits you.[n][f 2 7 10][f 0 4][e]

[msg MSG_0862 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 968]You cannot avoid death. To live is to die;[n]they are one in the same...[n][f 2 7 10][f 0 4][e]

[msg MSG_0863 [Nyx Avatar]]
[f 0 8 65278][f 1 31][f 2 9 5 969]Let us finish this. It is the path[n]of your choosing.[n][f 2 7 10][f 0 4][e]

[msg MSG_0864 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 864]Who is that...?[n][f 2 7 10][f 0 4][e]

[msg MSG_0865 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 865]Ummm... Is it just me, or does it[n]seem like she wants to fight...?[n][f 2 7 10][f 0 4][e]

[msg MSG_0866 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 866]What!? Her power is unbelievable![n]...Who IS she!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0867 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 9 5 970][f 0 31 16 10 1 1]I make my living as an elevator[n]attendant, but...[n][f 2 7 10][f 0 4][e]

[msg MSG_0868 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 11 5 971][f 0 31 16 10 1 1]I know several effective ways of[n]inflicting pain.[n][f 2 7 10][f 0 4][e]

[msg MSG_0869 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 11 5 972][f 0 31 16 10 1 1]Don't worry, I'm not as fragile[n]as I look. Try to kill me... if[n]you can.[n][f 2 7 10][f 0 4][e]

[msg MSG_0870 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 9 5 973][f 0 31 16 10 1 1]Magnificent! Your power is every bit[n]as impressive as I'd hoped...[n][f 2 7 10][f 0 4][e]

[msg MSG_0871 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 11 5 974][f 0 31 16 10 1 1]But, the curtain has just risen...[n]Show me your best performance![n][f 2 7 10][f 0 4][e]

[msg MSG_0872 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 9 5 975][f 0 31 16 10 1 1]Marvelous... You wield such power.[n][f 2 7 10][f 0 4][e]

[msg MSG_0873 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 11 5 976][f 0 31 16 10 1 1]The performance is underway.[n]I shall give you something to[n]remember![n][f 2 7 10][f 0 4][e]

[msg MSG_0874 [Elizabeth]]
[f 0 8 65278][f 1 31][f 2 9 5 977][f 0 31 16 10 1 1]Now, I give you the grand finale![n][f 2 7 10][f 0 4][e]

[msg MSG_0875 [Metis]]
[f 0 8 65278][f 1 31][f 2 9 3 1205][f 0 31 29 10 6 1]You must stand aside.[n][f 2 7 10][f 0 4][e]

[msg MSG_0876 [Metis]]
[f 0 8 65278][f 1 31][f 2 9 3 1206][f 0 31 29 10 6 1]Don't resist, and I won't hurt you...![n][f 2 7 10][f 0 4][e]

[msg MSG_0877 [Metis]]
[f 0 8 65278][f 1 31][f 2 9 3 1207][f 0 31 29 10 6 1]Argh...[n][f 2 7 10][f 0 4][e]

[msg MSG_0878 [Metis]]
[f 0 8 65278][f 1 31][f 2 9 3 1208][f 0 31 29 10 6 1]Please... Don't resist...[n][f 2 7 10][f 0 4][e]

[msg MSG_0879 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1089][f 0 31 2 12 5 1]Why's it using Io...!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0880 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1090][f 0 31 2 12 5 1]Why's it using Isis...!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0881 [Aigis]]
[f 0 8 65278][f 1 31][f 2 9 3 1094][f 0 31 3 9 4 1]Athena...[n][f 2 7 10][f 0 4][e]

[msg MSG_0882 [Aigis]]
[f 0 8 65278][f 1 31][f 2 9 3 1094][f 0 31 3 9 4 1]Palladion...[n][f 2 7 10][f 0 4][e]

[msg MSG_0883 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 3 1099][f 0 31 4 12 4 1]No... Penthesilea!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0884 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 3 1100][f 0 31 4 12 4 1]No... Artemisia!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0885 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1103][f 0 31 5 12 3 1]Hey! Nobody copies my Hermes!![n][f 2 7 10][f 0 4][e]

[msg MSG_0886 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1104][f 0 31 5 12 3 1]Trismegistos...[n]You damn copycat![n][f 2 7 10][f 0 4][e]

[msg MSG_0887 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1109][f 0 31 7 12 3 1]The hell...? That's Polydeuces![n][f 2 7 10][f 0 4][e]

[msg MSG_0888 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1110][f 0 31 7 12 3 1]The hell...? That's Caesar![n][f 2 7 10][f 0 4][e]

[msg MSG_0887_2 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1109][f 0 31 7 12 3 1]The hell...? That's Polydeuces![n][f 2 7 10][f 0 4][e]

[msg MSG_0928 [Ken]]
[f 0 8 65278][f 1 31][f 2 9 3 1112][f 0 31 8 12 4 1]How can he use Kala-Nemi...?[n][f 2 7 10][f 0 4][e]

[msg MSG_0889]
[f 0 8 65278][f 1 31][f 2 9 3 686][f 0 31 10 12 3 1]> Koromaru is furious.[n][f 2 7 10][f 0 4][e]

[msg MSG_0890 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1230][f 0 31 7 12 3 1]We'll see whose will is stronger![n][f 2 7 10][f 0 4][e]

[msg MSG_0891 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1231][f 0 31 7 12 3 1]Hmph... That was nothing.[n][f 2 7 10][f 0 4][e]

[msg MSG_0892 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1232][f 0 31 7 12 3 1]Tch... Not bad... But I'm[n]not going down![n][f 2 7 10][f 0 4][e]

[msg MSG_0893 [Akihiko]]
[f 0 8 65278][f 1 31][f 2 9 3 1233][f 0 31 7 12 3 1]Rrgh... I'm not through yet.[n]Let's see how much power you[n]really have![n][f 2 7 10][f 0 4][e]

[msg MSG_0894 [Ken]]
[f 0 8 65278][f 1 31][f 2 11 3 1235][f 0 31 8 12 3 1]If you don't take this seriously...[n]You'll be hurt.[n][f 2 7 10][f 0 4][e]

[msg MSG_0895 [Ken]]
[f 0 8 65278][f 1 31][f 2 9 3 1236][f 0 31 8 12 3 1]You're strong...![n][f 2 7 10][f 0 4][e]

[msg MSG_0896 [Ken]]
[f 0 8 65278][f 1 31][f 2 9 3 1237][f 0 31 8 12 3 1]All right... it's time to[n]get serious![n][f 2 7 10][f 0 4][e]

[msg MSG_0897 [Ken]]
[f 0 8 65278][f 1 31][f 2 9 3 1238][f 0 31 8 12 3 1]I won't give up![n][f 2 7 10][f 0 4][e]

[msg MSG_0898 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1225][f 0 31 5 12 3 1]Get ready, 'cause here I come![n][f 2 7 10][f 0 4][e]

[msg MSG_0899 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1226][f 0 31 5 12 0 1]Dude, you're pretty tough, Ai-chan.[n]But you're not the only one![n][f 2 7 10][f 0 4][e]

[msg MSG_0900 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1227][f 0 31 5 12 3 1]Heh... I never thought I'd be[n]on the receiving end of your[n]gadgets again![n][f 2 7 10][f 0 4][e]

[msg MSG_0901 [Junpei]]
[f 0 8 65278][f 1 31][f 2 9 3 1228][f 0 31 5 12 3 1]This ain't good... I better go[n]all-out![n][f 2 7 10][f 0 4][e]

[msg MSG_0902]
[f 0 8 65278][f 1 31][f 2 11 3 703][f 0 31 10 12 3 1]> Koromaru is fully prepared.[n][f 2 7 10][f 0 4][e]

[msg MSG_0903]
[f 0 8 65278][f 1 31][f 2 9 3 714][f 0 31 10 12 3 1]> Koromaru still seems healthy.[n][f 2 7 10][f 0 4][e]

[msg MSG_0904]
[f 0 8 65278][f 1 31][f 2 9 3 701][f 0 31 10 12 3 1]> Koromaru is getting tired.[n][f 2 7 10][f 0 4][e]

[msg MSG_0905]
[f 0 8 65278][f 1 31][f 2 9 3 687][f 0 31 10 12 4 1]> Koromaru seems to be in pain.[n][f 2 7 10][f 0 4][e]

[msg MSG_0906 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1215][f 0 31 2 12 3 1]Get ready, cause I'm gonna tear[n]you apart![n][f 2 7 10][f 0 4][e]

[msg MSG_0907 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1216][f 0 31 2 12 3 1]What's the matter!? Is that all[n]you've got!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0908 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1217][f 0 31 2 12 3 1]I barely even feel a thing![n][f 2 7 10][f 0 4][e]

[msg MSG_0909 [Yukari]]
[f 0 8 65278][f 1 31][f 2 9 3 1218][f 0 31 2 12 3 1]I can't lose... I WILL NOT LOSE![n][f 2 7 10][f 0 4][e]

[msg MSG_0910 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 3 1221][f 0 31 4 12 3 1]I won't hold back![n][f 2 7 10][f 0 4][e]

[msg MSG_0911 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 3 1224][f 0 31 4 12 3 1]I knew you wouldn't be an easy[n]opponent...[n][f 2 7 10][f 0 4][e]

[msg MSG_0912 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 3 1223][f 0 31 4 12 3 1]Impressive... But I'll fight to[n]the bitter end![n][f 2 7 10][f 0 4][e]

[msg MSG_0913 [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 11 3 1220][f 0 31 4 12 3 1]Show me your resolve![n][f 2 7 10][f 0 4][e]

[msg MSG_0914 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 1016]The flow of power...![n][f 2 7 10][f 0 4][e]

[msg MSG_0915 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 1017]Be careful! It's going to use that[n]attack again...![n][f 2 7 10][f 0 4][e]

[msg MSG_0916 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 990]It's so... powerful...[n][f 2 7 10][f 0 4][e]

[msg MSG_0917 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 991]You won't be able to survive much[n]more of that. We have to think of[n]a way to avoid it...[n][f 2 7 10][f 0 4][e]

[msg MSG_0918 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 1005]Is the attack getting stronger...!?[n][f 2 7 10][f 0 4][e]

[msg MSG_0919 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 1018]You can't possibly endure another[n]one!! You must prevent it...![n][f 2 7 10][f 0 4][e]

[msg MSG_0920 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 992]The enemy is gathering power...![n][f 2 7 10][f 0 4][e]

[msg MSG_0921 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 993]If you attack now... You might be[n]able to break its concentration![n][f 2 7 10][f 0 4][e]

[msg MSG_0922 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 995]...I think it can't move![n][f 2 7 10][f 0 4][e]

[msg MSG_0923 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 996]This is your chance![n][f 2 7 10][f 0 4][e]

[msg MSG_0924 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 1089]What is that light...? I don't like[n]the looks of it...[n][f 2 7 10][f 0 4][e]

[msg MSG_0925 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 1090]I don't know anything about that[n]attack. Be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_0926 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 1003]That attack's strength has increased[n]dramatically...![n][f 2 7 10][f 0 4][e]

[msg MSG_0927 [Fuuka]]
[f 0 8 65278][f 1 31][f 2 11 5 1004]We must find some way to stop it...[n][f 2 7 10][f 0 4][e]

[msg MSG_1EA_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 63]The enemy is stronger than you are[n]accustomed to. Proceed with caution![n][f 2 7 10][f 0 4][e]

[msg MSG_1CE_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 76]It must be guarding this area...[n]It's strong, so be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_1CF_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 70]It seems you've attracted the[n]guardian's attention. Its Arcana[n]is the Chariot.[n][f 2 7 10][f 0 4][e]

[msg MSG_1D0_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 79]A guardian... I'm afraid you'll have[n]to defeat it to proceed.[n][f 2 7 10][f 0 4][e]

[msg MSG_1D1_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 66]Its Arcana is the Empress. It's[n]a guardian, so it'll be a difficult[n]fight![n][f 2 7 10][f 0 4][e]

[msg MSG_1D6_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 77]It seems to be protecting this area.[n]It's strong, so don't let your guard[n]down![n][f 2 7 10][f 0 4][e]

[msg MSG_1D7_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 67]It's a strong one; be careful![n]I sense the Emperor Arcana.[n][f 2 7 10][f 0 4][e]

[msg MSG_1D8_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 78]Don't underestimate this one;[n]it's more powerful than it seems![n][f 2 7 10][f 0 4][e]

[msg MSG_1D9_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 68]The Hierophant, huh? This one will[n]prove to be a challenge![n][f 2 7 10][f 0 4][e]

[msg MSG_1DA_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 81]This is no ordinary Shadow.[n]Be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_1DB_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 69]Its Arcana is the Lovers.[n]It's strong, so be ready![n][f 2 7 10][f 0 4][e]

[msg MSG_1DC_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 80]It's not a normal Shadow.[n]Attack with all your might![n][f 2 7 10][f 0 4][e]

[msg MSG_1DD_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 64]The Magician, huh... This will be[n]tough; stay sharp![n][f 2 7 10][f 0 4][e]

[msg MSG_1DE_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 63]The enemy is stronger than you are[n]accustomed to. Proceed with caution![n][f 2 7 10][f 0 4][e]

[msg MSG_1DF_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 74]I sense the Strength Arcana.[n]This Shadow is more powerful[n]than most.[n][f 2 7 10][f 0 4][e]

[msg MSG_1E0_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 77]It seems to be protecting this area.[n]It's strong, so don't let your guard[n]down![n][f 2 7 10][f 0 4][e]

[msg MSG_1E1_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 78]Don't underestimate this one;[n]it's more powerful than it seems![n][f 2 7 10][f 0 4][e]

[msg MSG_1E2_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 72]I sense the Hermit Arcana...[n]This foe is very powerful![n][f 2 7 10][f 0 4][e]

[msg MSG_1E3_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 81]This is no ordinary Shadow.[n]Be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_1E4_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 73]This guardian's Arcana is Fortune,[n]but the battle won't be won by luck![n][f 2 7 10][f 0 4][e]

[msg MSG_1E5_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 79]A guardian... I'm afraid you'll have[n]to defeat it to proceed.[n][f 2 7 10][f 0 4][e]

[msg MSG_1E6_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 76]It must be guarding this area...[n]It's strong, so be careful![n][f 2 7 10][f 0 4][e]

[msg MSG_1E7_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 71]This is an important battle...[n]Your opponent's Arcana is Justice.[n][f 2 7 10][f 0 4][e]

[msg MSG_1E8_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 80]It's not a normal Shadow.[n]Attack with all your might![n][f 2 7 10][f 0 4][e]

[msg MSG_1E9_M [Mitsuru]]
[f 0 8 65278][f 1 31][f 2 9 4 75]Stay calm, and you can defeat this[n]guardian. Its Arcana is the Hanged[n]Man.[n][f 2 7 10][f 0 4][e]

[msg MSG_1EA_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 14]This is a tough one! Watch each[n]others' backs![n][f 2 7 10][f 0 4][e]

[msg MSG_1CE_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 27]It seems to be guarding this area![n]Be careful, it's powerful![n][f 2 7 10][f 0 4][e]

[msg MSG_1CF_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 21]The enemy is a Chariot. Ordinary[n]Shadows pale in comparison![n][f 2 7 10][f 0 4][e]

[msg MSG_1D0_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 30]It seems you have to defeat this one[n]to move on.[n][f 2 7 10][f 0 4][e]

[msg MSG_1D1_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 17]My goodness, this one's strong![n]Its Arcana is the Empress.[n][f 2 7 10][f 0 4][e]

[msg MSG_1D6_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 28]This is not just a random Shadow...[n]It seems to be guarding this area![n][f 2 7 10][f 0 4][e]

[msg MSG_1D7_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 18]This Shadow is an Emperor. It must be[n]watching over this area![n][f 2 7 10][f 0 4][e]

[msg MSG_1D8_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 29]Be ready! I sense it's a strong one![n][f 2 7 10][f 0 4][e]

[msg MSG_1D9_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 19]Be careful... This Hierophant is[n]quite powerful![n][f 2 7 10][f 0 4][e]

[msg MSG_1DA_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 32]This one's dangerous. Stay focused![n][f 2 7 10][f 0 4][e]

[msg MSG_1DB_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 20]Its Arcana is the Lovers.[n]It's a strong foe![n][f 2 7 10][f 0 4][e]

[msg MSG_1DC_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 31]This is no ordinary enemy.[n]Don't let your guard down![n][f 2 7 10][f 0 4][e]

[msg MSG_1DD_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 15]It seems like it's exceptionally strong![n]Its Arcana is the Magician.[n][f 2 7 10][f 0 4][e]

[msg MSG_1DE_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 14]This is a tough one! Watch each[n]others' backs![n][f 2 7 10][f 0 4][e]

[msg MSG_1DF_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 25]Its Arcana is Strength! This won't[n]be easy![n][f 2 7 10][f 0 4][e]

[msg MSG_1E0_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 28]This is not just a random Shadow...[n]It seems to be guarding this area![n][f 2 7 10][f 0 4][e]

[msg MSG_1E1_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 29]Be ready! I sense it's a strong one![n][f 2 7 10][f 0 4][e]

[msg MSG_1E2_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 23]Its Arcana is the Hermit. This will be[n]a tough battle![n][f 2 7 10][f 0 4][e]

[msg MSG_1E3_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 32]This one's dangerous. Stay focused![n][f 2 7 10][f 0 4][e]

[msg MSG_1E4_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 24]Its Arcana is Fortune. This will be[n]a difficult fight![n][f 2 7 10][f 0 4][e]

[msg MSG_1E5_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 30]It seems you have to defeat this one[n]to move on.[n][f 2 7 10][f 0 4][e]

[msg MSG_1E6_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 27]It seems to be guarding this area![n]Be careful, it's powerful![n][f 2 7 10][f 0 4][e]

[msg MSG_1E7_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 22]This Shadow is a formidable foe![n]Its Arcana is Justice.[n][f 2 7 10][f 0 4][e]

[msg MSG_1E8_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 31]This is no ordinary enemy.[n]Don't let your guard down![n][f 2 7 10][f 0 4][e]

[msg MSG_1E9_F [Fuuka]]
[f 0 8 65278][f 1 31][f 2 9 5 26]The Hanged Man... That's this[n]guardian's Arcana![n][f 2 7 10][f 0 4][e]

